version: '3'
volumes:
  ngpet-db:
services:
  ngpet:
    image: thecodingmachine/php:7.4-v4-apache-node14
    container_name: ngpet
    ports:
      - "8101:80"
      - "3110:3000"
      - "3111:3001"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: public/
  ngpet-db:
    image: mysql:5.7
    ports:
      - "3320:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ngpet
      MYSQL_USER: ngpet
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ngpet-db:/var/www/html
  ngpet-mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1027:1025 # smtp server
      - 8027:8025 # web ui
